language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: qsqaXOWKegQLiWFGCdX+kWPLvLoH+1BA13UW/KFB8ZERYb9O960Pll5220o9TeSMWaZtIlQ9Fv4li1w+bLqPz8d80Tf27F8vaPy4N3akNgYgSpynM7Q7l7SPt4clQVSeohw8v97s662ZtuNxkoLMoHSbgRhR5HilFsieGQohmoxvK8MDjd5DpE6YhfRshR3kdp4UdnGQ7tYjvAMXNrcU7hDPmYPkfVs0myGcT9p6/2DYqG1E5iMYKRmhksKkAUt8WO3KmCGD6UWrlgu82VSUjyZcQCDKHQyvsNW1FEa2vWMB0BP7BCmnt8BtTO17l8rus6ZzmJp9shXhvFFcyGmRwjpJYWk9/+VC6WhDw0ENu90sjoRkJL6v/k92ZMpiYbb8u50FWieeirlcNFPNRDILX7VPkHSOgsUL3T5396hN8i073pPehkxkjxkLDUFqtxcbaDkArlqxylBUFi1zlqB+EHPSoJFAo97maAL3kC0IY8ANnaeUfxr5gcZDel65VYJH4mAZoE14oaY242j7Zq2AqYgSalr96stZa34i4I5Jxvyv6l1Z3yhpTkj8tjugAg08AshWW4+LBB7XRKsL50alY0sV3bv3SY7GQRZrjZ4TByodKfrVSMrq6IsyAgieGj0wbSOVM8Q3NOTqmzG01qUApUiP4KVjox/HX2q3yGiJfDU=
  app: express-reference
  on:
    repo: primaulia/express-reference

